### ISSUE TITLE
DO NOT CLOSE THIS ISSUE:  it does not support live changes for Meteor Framework

### ISSUE THREAD

**Issue by shaunstanislaus** [localtunnel/localtunnel#100]
Dear Mr. Owner,

when will you be able to look into supporting live refresh upon certain frameworks like Meteor that automatically refreshes the page.

**Comment by defunctzombie** [comment]
I don't know what the core issue is here. Maybe websocket isn't working, maybe there is some other way it wants to communicate with the server. I am closing this issue because I am not going to fix it but will review a PR if you yourself find the issue.

**Comment by defunctzombie** [comment]
Please do not open another issue and asking to not close an issue is not an ideal way to go about getting a project to take your issue more seriously. I understand that it is not working for you but if you do some research and report back more details and potential fixes then your issue might be taken more seriously. You must imagine that to me your issue is simply "it doesn't work for me, solve my problems for me" and doesn't actually give me any details about what actual thing is not working or debugging why or anything helpful.
