### ISSUE TITLE
Support localhost absolute paths

### ISSUE THREAD

**Issue by neverfox** [localtunnel/localtunnel#103]
When implementing [this fix](http://stackoverflow.com/a/34133809/2128319), it breaks localtunnel support, since I'm assuming lt depends on relative paths. See [issue here](https://github.com/davezuko/react-redux-starter-kit/issues/275) where implementing that advice broke the ability to use localtunnel with react-redux-starter-kit projects.

**Comment by defunctzombie** [comment]
Sorry, I am not quite understanding the issue here. What does it mean that localtunnel doesn't support absolute or relative paths? From the issue it seems that a page opened via localtunnel was then trying to make a request on localhost but again not sure I fully understand the issues here. Could you please clarify/summarize what the problem is and intended way it should work. If there is an example I can download and run to reproduce that would also be awesome.

**Comment by neverfox** [comment]
For an example, you can simply clone and run [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit) and see that it doesn't work with localtunnel, which it did prior to [this commit](https://github.com/davezuko/react-redux-starter-kit/commit/2076d1e4c47c57e93c93f20b5370e7cbe80bf39d), which replaced relative paths with absolute paths to localhost. The reason the change was made was because of the problem discussed in the first link above.

> From the issue it seems that a page opened via localtunnel was then trying to make a request on localhost

That's right. What I'm suggesting is that, if there's a way for localtunnel to recognize these requests as being against localhost and the tunneled port, perhaps it could handle those absolute path requests. Then again, maybe that would be impossible or undesirable. If you have any suggestions about a localtunnel compatible way to deal with the CSS assets issue discussed in that link, I would appreciate some guidance.

**Comment by defunctzombie** [comment]
How could localtunnel recognize a request to localhost? The browser will just send the request to localhost and not to localtunnel domain unless I am missing something. Prior to that commit, the request for resources would have been to a relative path and the browser would have sent that to the same domain as the page (the localtunnel domain) but now that won't happen and when a user opens this starter kit from a localtunnel domain, the requests it will make will tell the browser to request from localhost:port which obviously the target testing user won't have a server running locally to service that request (since they visited the page presumably hosted by someone else for demo).

**Comment by neverfox** [comment]
As I feared. I thought there might have been some magic going on, but it's just standard behavior. Thanks for taking a look.
