### ISSUE TITLE
Bad request is showing on https local network.

### ISSUE THREAD

**Issue by dheerajgoyal38** [localtunnel/localtunnel#153]
I have a secure https server set up on my local on port 443.
lt --port 443
the above command will generates a link.But when i try to access the link it is giving me the following error on browser.

**Bad Request**

**Your browser sent a request that this server could not understand.**
**Reason: You're speaking plain HTTP to an SSL-enabled server port.**
**Instead use the HTTPS scheme to access this URL, please.**

**Comment by austinginder** [comment]
I think the issue is that localtunnel's server is tunneling back to your local computer using the http protocol. I couldn't find a way to tell the server to use https as the protocol. 

I suggest adding the flag `--protocol https`. So something like `lt --port 443 --protocol https` would tell localtunnel's server to tunnel with https instead of http. I'd guess that's require some updates to the server as well as the client.

**Comment by defunctzombie** [comment]
The tunnel back to your local server uses http. I don't particularly plan to support https tunnels back to your local server since for development using http is ok. I will however gladly review PRs that add this functionality.
