### ISSUE TITLE
413 Request entity to Large

### ISSUE THREAD

**Issue by syzer** [localtunnel/localtunnel#225]
While posting simple iphone pictures via form uplad
I get 
413 From nginx
Can you please set the entity size a bit bigger?
http {
        client_max_body_size 50M;
}

**Comment by defunctzombie** [comment]
Localtunnel is designed for testing webhooks, client apis, and exposing short demos; are you able to upload your pictures by accessing your local server via `localhost` instead of going through localtunnel for local development? There are resource limits on localtunnel because it is not meant to be a production deployment of your service.

**Comment by syzer** [comment]
yeah.. we do demo apps on hackatons with pictures or videos from iphone/android... they are quite big these days

**Comment by dmk255** [comment]
@syzer - 50M is pretty big. Can you chunk your requests or is this the size of a single static asset?
