### ISSUE TITLE
Permit more than just HTTP?

### ISSUE THREAD

**Issue by infodox** [localtunnel/localtunnel#23]
An option to allow a direct socket connection would be nice, for example, if I wish to permit someone to access my box via SSH/FTP/whatever, being able to forward those protocols would be nice.

Have the default listener set to 80 on the localtunnel.me 'forwarded host' or whatever port works for you.

Just an idea, but it would be a very nice function :)

**Comment by acrogenesis** [comment]
ngrok does permit tcp connections

**Comment by defunctzombie** [comment]
I am not against it but don't have the time to look into what it would take
to accomplish it. I also don't view it as a priority since it is not the
main focus of this tool.

**Comment by jamesokbo** [comment]
Just to be clear, Websockets are still not supported on the hosted server, right? Sorry if they aren't... I've been looking for a service that does this for quite some time now, since I don't have the time to code it (or better yet, to learn how to code it and then do it) myself either...
I do believe this kind of service would open a door to bidirectional communications between local devices. I know there are some services that offer this, Ngrok is one of them, but their payment plans don't seem right for what I need...

**Comment by defunctzombie** [comment]
@jamesokbo websockets should be supported just fine on the hosted server. If they are not, it is likely a bug.

**Comment by jamesokbo** [comment]
Was this recently implemented? :)

**Comment by defunctzombie** [comment]
No, iirc websocket support has existed for a while

**Comment by jamesokbo** [comment]
lol ok! thank you very much, I'll try it as soon as I can
