### ISSUE TITLE
Deceptive site ahead

### ISSUE THREAD

**Issue by deepakmahakale** [localtunnel/localtunnel#331]
**Deceptive site ahead**

Browser: Chrome
Version: 78.0.3904.108

![image](https://user-images.githubusercontent.com/14993828/70132568-816ee000-16aa-11ea-9063-85f904497a80.png)
![image](https://user-images.githubusercontent.com/14993828/70132650-a9f6da00-16aa-11ea-8fe7-ea7acba511fe.png)

**Comment by operat** [comment]
There seems to be a problem with the SSL certificate. FF shows this: "Peer's Certificate has been revoked."

![Screen Shot 2019-12-05 at 20 52 14-fullpage](https://user-images.githubusercontent.com/1681615/70268914-a2fec300-17a1-11ea-93c2-781e148ecb85.png)

**Comment by WBDC** [comment]
I believe this is to do with the Expired certificate, although the cert shows that it expired on the 10th December. There is a ticket raised under #332

**Comment by arunarn2** [comment]
Can this be fixed ASAP?

**Comment by rrigoni** [comment]
The service is not working. Can we please update the certificate?

**Comment by Pirngruber** [comment]
localtunnel.me is now up and running again :)
i took over the hosting and maintenance part from @defunctzombie so feel free to use it as before.

let us know if you have further questions

**Comment by TheBoroer** [comment]
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain *.loca.lt instead of *.localtunnel.me (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

**Comment by TheBoroer** [comment]
@defunctzombie feel free to close this issue.
