### ISSUE TITLE
Update the SSL of localtunnel.me

### ISSUE THREAD

**Issue by LewaIngame** [localtunnel/localtunnel#338]
Hello can you update the ssl of local tunnel beacause he not work

**Comment by Pirngruber** [comment]
localtunnel.me is now up and running again :)
i took over the hosting and maintenance part from @defunctzombie so feel free to use it as before.

let us know if you have further questions

**Comment by noriellecruz** [comment]
The ssl issue still occurs

**Comment by Pirngruber** [comment]
I see i see, i‘m on it ;)

**Comment by Pirngruber** [comment]
soo finally done @noriellecruz everything should be fine now.

**Comment by rubystar** [comment]
https://localtunnel.me/ is currently down. Giving 502 Bad Gateway. Thanks

**Comment by TheBoroer** [comment]
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain *.loca.lt instead of *.localtunnel.me (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

**Comment by TheBoroer** [comment]
@defunctzombie feel free to close this issue.
