### ISSUE TITLE
Seems localtunnel server is down

### ISSUE THREAD

**Issue by vlad-groznov** [localtunnel/localtunnel#340]
Logs:
```
tunnel server offline: Request failed with status code 502, retry 1s
tunnel server offline: Request failed with status code 502, retry 1s
tunnel server offline: Request failed with status code 502, retry 1s
tunnel server offline: Request failed with status code 502, retry 1s
tunnel server offline: Request failed with status code 502, retry 1s
```

**Comment by theaklair** [comment]
Also, I've spotted that someone got `localtunnel.me` domain name, and currently it redirects to `https://pirngruber.github.io/localtunnel-www/`, which is also has fork of localtunnel repo.

**Comment by rubystar** [comment]
Any update on this please

**Comment by igauravsehrawat** [comment]
This is repo is no more active. You can use ngrok.
I have seen lot of corporate network blocking ngrok and similar sites.

If you have your own person domain.
Checkout my blog post for building your ngrok in 4 easy steps 
https://igauravsehrawat.com/build-your-own-ngrok-4-easy-steps/

**Comment by TheBoroer** [comment]
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain *.loca.lt instead of *.localtunnel.me (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

@theaklair The original maintainer isn't interested in investing his time into hosting localtunnel.me anymore so he's let other volunteers host it. I've taken over from @Pirngruber as of last week + added some extra things to the server to fight phishing abuse.

**Comment by TheBoroer** [comment]
@defunctzombie feel free to close this issue.
