### ISSUE TITLE
Localtunnel is down

### ISSUE THREAD

**Issue by lhr000lhrmega** [localtunnel/localtunnel#343]
Currently, local tunnel's service is not available.
What's the problem?

**Comment by uqcgreen** [comment]
Yes, when I try to open a tunnel it just hangs with no message (I assume it would eventually timeout), and the website doesn't respond.

**Comment by mark-ukr** [comment]
When i set environment `DEBUG="localtunnel:*"`, i see the following logs:

```
  localtunnel:client tunnel server offline: connect ECONNREFUSED 92.51.164.34:443, retry 1s +1s
```

**Comment by Capriatto** [comment]
Yeah, it's down :c

**Comment by rushi** [comment]
Paging @Pirngruber localtunnel.me is down. Are you able to fix that?

**Comment by alaasdk** [comment]
still Down : - (

**Comment by jimthedev** [comment]
The author mentions trying out another service on his twitter because he doesn't work on localtunnel much anymore: https://twitter.com/defunctzombie/status/1219768900537081856

**Comment by aakashapoorv** [comment]
Use `lt -h "http://lt.serverless.social:8080" -p PORT`

**Comment by ngelx** [comment]
> Use `lt -h "http://serverless.social" -p PORT`

Thanks @aakashapoorv for running this server. Any chance to be able to add SSL (https) support.

**Comment by gtpatchaya** [comment]
lt -h "http://serverless.social" -p PORT  

It worked for me.
thank you @aakashapoorv

**Comment by carlos22ivan** [comment]
works correctly, thank you @aakashapoorv

**Comment by besoeasy** [comment]
why not use ngrok ?

**Comment by lhr000lhrmega** [comment]
> why not use ngrok ?

as it cannot customise the subdomain.

**Comment by besoeasy** [comment]
neither can http://serverless.social atleast not for me

**Comment by KaKi87** [comment]
Doesn't anyone has an issue with serverless.social not being documented and not supporting SSL ?

**Comment by trd** [comment]
> why not use ngrok ?

ngrok is down too these days.

**Comment by JonathanSouthern** [comment]
> Ngrok is down, too, these days.

Just used Ngrok with SSL today, maybe it was down temporarily

**Comment by etewiah** [comment]
Would be good to have some clear way of warning people off obsolete libraries.  There is a real danger of opening up vulnerabilities by using something like localtunnel now

**Comment by Readyfreddy33** [comment]
> 
> 
> Use `lt -h "http://serverless.social" -p PORT`

I tried it but no luck, it stays blank, heres my line
lt -h "http://serverless.social" -p 80

am i missing something?

**Comment by Capriatto** [comment]
it was working days ago but currently down too.

**Comment by eparizzi** [comment]
Any chance to support HTTPS on serverless.social? A lot of services won't call a non-HTTPS endpoint.

**Comment by przano** [comment]
> Any chance to support HTTPS on serverless.social? A lot of services won't call a non-HTTPS endpoint.

This. Yes please

**Comment by novaknole** [comment]
Still down? i have tried everything , but with no chance. 

using the above solution says: `your url is undefined`.

the normal way says: `nothing. it just hangs`.

**Comment by darkvertex** [comment]
Still down for me also. Too bad. :cry:

**Comment by aakashapoorv** [comment]
@here follow server status and ask questions here `https://discord.gg/WHBS3uX`

**Comment by alexellis** [comment]
Folks may also like inlets, which you can self host easily and comes with optional cloud and Kubernetes integration. https://inlets.dev

**Comment by dandv** [comment]
https://serveo.net/ used to work, but not any more...

**Comment by alexellis** [comment]
Try inlets it's open source and free to use. You can host your own exit-server for 5 USD / mo. https://itnext.io/get-started-with-free-http-and-websocket-tunnels-30c9ac3fd247

**Comment by KaKi87** [comment]
Serveo was the best option indeed.

**Comment by shoverian** [comment]
If you just need a quick solution without any special config requirements. 

[ngrok](https://ngrok.com/) fixed my problem (thanks @besoeasy) I had a local server running ~5min. 

This might not be the right solution for everyone, but it works.

**Comment by darkvertex** [comment]
http://localhost.run/ is a nice alternative also and the best part is it requires no software; `ssh` is enough.

Say you want to forward port 80, it's simply:
```ssh -R 80:localhost:80 yourproject@ssh.localhost.run```

(No accounts needed for the free tier but the hostnames are intentionally random to curb abuse.)

**Comment by TheBoroer** [comment]
Hey everyone ,
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain `*.loca.lt` instead of `*.localtunnel.me` (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

**Comment by KaKi87** [comment]
> I don't have full DNS control

Why not ?

**Comment by TheBoroer** [comment]
> > I don't have full DNS control
> 
> Why not ?

Because the original maintainer of the project owns and controls the domain and wasn't going to transfer the domain (or provide his namecheap account login) to a random stranger. I just offered to host the server/site so others like me can continue using the service without needing to self-host it. He agreed and pointed some DNS records to me which makes `lt` work again without needing to specify the host argument. To be able to give out https sudomains I got my own domain (loca.lt) and a free letsencrypt wildcard SSL certificate (via dns challenge) and here we are! :)

An assigned subdomain will work under both domains. Example:

- test.loca.lt works with HTTP and HTTPS.  
- test.localtunnel.me will also work but only HTTP. HTTPS will give you a certificate error in the browser.

**Comment by KaKi87** [comment]
So you were even able to contact him at all ?
Then why wouldn't he just continue to host it ?
And wouldn't it be logical for him to give up the domain name if he won't ?
To finish, what about updates ? I suppose he still owns the NPM `localtunnel` package so will be handle module updates when they'll be necessary ?

**Comment by TheBoroer** [comment]
Yeah I contacted him to offer my server hosting services for this project

> So you were even able to contact him at all ?
> Then why wouldn't he just continue to host it ?
> And wouldn't it be logical for him to give up the domain name if he won't ?
> To finish, what about updates ? I suppose he still owns the NPM `localtunnel` package so will be handle module updates when they'll be necessary ?


Yup, I was able to reach him to offer my server hosting services for this project. He said he doesn't have the time to spend on this project right now (including dealing with abuse on the public localtunnel server). He said if I wanted to help maintain it I could just do pull requests and tag in them and he'll approve them whenever he has free time. Maybe once other contributors prove themselves to be trustworthy, he'll transfer the domain or add other official maintainers.

**Comment by KaKi87** [comment]
So the guy wants you to prove you're trustworthy while he proved himself not to be when he stopped hosting localtunnel without a warning. Grrrr...

**Comment by TheBoroer** [comment]
loll keep calm and dev on.

I would do the same, randoms on the internet can't always be trusted right away. @defunctzombie is pretty trustworthy and was basically providing an open reverse proxy / relay free of charge...and good servers aren't free. The server/client packages work great and do the job. You should be thanking him and other contributors for building, maintaining and hosting such a great dev tool. If you're annoyed at the free service being down (which isn't the maintainer's fault since someone else volunteered to host it and decided to stop randomly), you should look into [ngrok.com](https://ngrok.com/pricing) or host it yourself on your own domain.

There's also tons of abuse going through localtunnel.me including people using it to host phishing portals, distribute malware, or host malware data dump sites. Just an example of my experience hosting this service so far...during my first 24 hours of hosting the service, using my own loca.lt domain, the entire domain and all subdomains were flagged by google for phishing/deceptive site (meaning most browsers got a red warning screen smh).

**Comment by TheBoroer** [comment]
@defunctzombie feel free to close this issue.

**Comment by mridah** [comment]
@TheBoroer first of all thanks for keeping this project alive!!! 

Secondly, I am currently trying to self host this on my website. I've pointed my dns records and all and when I run the `lt` command on the local client machine, the server shows that it got a request and the client gets the url. But apart from that nothing happens - the browsers return 404 and after sometime the client connection automatically drops. 

Can you please help me out in how it set yours up?

**Comment by nicklesscs** [comment]
Is localtunnel down? wss was not generating new website at all

**Comment by neetu-mittal** [comment]
Is localtunnel down?

**Comment by ShayzaadKallan22** [comment]
Is local tunnel down?

**Comment by danielblnc** [comment]
Yep, it's down
