### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by richsatty** [localtunnel/localtunnel#350]
Error: unable to verify the first certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
at TLSSocket.emit (events.js:198:13)
at TLSSocket.EventEmitter.emit (domain.js:448:20)
at TLSSocket._finishInit (_tls_wrap.js:636:8)
code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

Do we have to inject cert/key/pem that could be used within localtunnel for the handshaking. Can't see any option to provide these certs

**Comment by TheBoroer** [comment]
Hey @richsatty,
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain `*.loca.lt` instead of `*.localtunnel.me` (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

**Comment by richsatty** [comment]
Hi Mate,

Amazing to here local tunnel is up again. Is this the same npm package to use and hope subdomain works as well now?



Satish Jaiswal
Senior Full Stack Developer / Architect
03 9525 0755 <tel:+61%203%209525%200755>
0470 295 527 <tel: 61470295527>
WeAreDigital.
making commerce better and easier - every day.
wearedigital.com.au <https://wearedigital.com.au/>

We are trialing a flexible working model - for me this means I generally won't be working on Wednesdays.
I will however be contactable on my mobile for urgent matters.

**Comment by TheBoroer** [comment]
@richsatty Yup! Same npm package, subdomains should work too. The only difference is the subdomains will be *.loca.lt instead of *.localtunnel.me  :)

**Comment by TheBoroer** [comment]
@defunctzombie feel free to close this issue.
