### ISSUE TITLE
How to avoid Friendly Reminder page and directly take to tunneled page ?

### ISSUE THREAD

**Issue by gaamaaresosa** [localtunnel/localtunnel#366]
Please suggest to avoid the below message page which is annoying.

Friendly Reminder

This website is served via a localtunnel. This is just a reminder to always check the website address you're giving personal, financial, or login details to is actually the real/official website.

Phishing pages often look similar to pages of known banks, social networks, email portals or other trusted institutions in order to acquire personal information such as usernames, passwords or credit card details.

**Comment by TheBoroer** [comment]
Unfortunately you can't avoid it at the moment.
You only see it once per tunneled subdomain per IP per 7 days. 
The page will only show up for requests coming from browsers. You can change your user-agent (via browser extensions or dev tools) to something non-standard like "localtunnel" to bypass the page for your own browser.

I've implemented this due to people abusing the publicly hosted service and use these free subdomain tunnels to host phishing portals, which then causes the entire *.loca.lt domain to get flagged for phishing...ruining it for everyone else.

I know it's annoying but it's a must have. Feel free to self-host your own localtunnel server on your own domain to avoid seeing this notice.

**Comment by gaamaaresosa** [comment]
Thank you so much for your prompt reply with explanation.

>>Feel free to self-host your own localtunnel server on your own domain to avoid seeing this notice.
Since I am new to these concepts, if I get step by step tutorial to make my own sever at DigitalOcean 
that would be highly appreciated.

**Comment by TheBoroer** [comment]
All you need is nodejs on your server and follow the instructions here: https://github.com/localtunnel/server

That should set you up with http, https is going to be a bit more involved and depends on your setup

**Comment by gaamaaresosa** [comment]
Thanks again...
let me learn more...

**Comment by derwaldgeist** [comment]
I am getting this message frequent times a day, although my IP never changes. This is very annoying, because it breaks some integration scenarios (like OAuth). I would really appreciate if there would be a way to disable it.

**Comment by TheBoroer** [comment]
Hey @derwaldgeist,
Do you have the tunnel subdomain/url change frequently during the day?
Remember this page shows up per subdomain/ip combination per 7 days.
This is to stop an evil person sending their victims a harmless cutecat.loca.lt url, followed by a facebook-security-check.loca.lt link days later after the victim already acknowledged the tunneled page.

If you want to disable it, change your browser useragent to something non-standard like `localtunnel` instead of the standard user agent like `Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36`.

I only show this page to requests coming from real looking browser user agents.

**Comment by derwaldgeist** [comment]
Hi @TheBoroer Thanks for the fast reply. No, my domain doesn't change at all.

**Comment by TheBoroer** [comment]
@derwaldgeist 
I think I''ve spotted the issue. Can you please let me know if it's still happening for you? 
I'll keep checking my own subdomain randomly throughout the day too

**Comment by gaamaaresosa** [comment]
I got DigitalOcean and tried to setup localtunnel like server with below steps.
I don't know how to proceed next.
Could you please help me ?
For our own server what is the client and how to setup in local system ?

1) In DigtalOcean I have created a Ubuntu Droplet
2) logged in via Putty from Window PC and done these commands

apt update -y
apt upgrade -y
apt install nodejs -y
apt install npm -y

git clone git://github.com/defunctzombie/localtunnel-server.git
cd localtunnel-server
npm install

apt install golang-golang-x-tools -y

bin/server --port 1234


3) I got this message from my droplet:

Setting up golang-golang-x-tools (1:0.0~git20191118.07fc4c7+ds-1) ...
Processing triggers for man-db (2.9.1-1) ...
root@ga:~/localtunnel-server/bin# server --port 1234
Defaulting to port 8080Listening on port 8080

Can I understand my server is ready for localtunnel ?
Now what to do in my local system (raspberry pi) ?

Please help me...
please recommend if some one has done step by step tutorial for freshers like me.

**Comment by derwaldgeist** [comment]
> @derwaldgeist
> I think I've spotted the issue & pushed a fix. Can you please let me know if it's still happening for you?
> I'll keep checking my own subdomain randomly throughout the day too

Thanks for the info. I'll keep an eye on it. Could it be that this also fixed the problem that subdomains can't be reclaimed if the tunnel has been stopped? Because it seems as I now reliably get the subdomain again, which is awesome.

**Comment by derwaldgeist** [comment]
@TheBoroer Unfortunately, the "Friendly reminder page" is still a problem. But the tunnel subdomain is now available much more reliably.

**Comment by derwaldgeist** [comment]
I also noticed that the "Friendly Reminder" page does not work if you use the app inside a web view on a mobile device. If I click on "Continue", nothing happens. I have to open the same page on my desktop browser before, otherwise the app would be "broken".

**Comment by derwaldgeist** [comment]
> But the tunnel subdomain is now available much more reliably.

Unfortunately, this did not last long. Today, even after many hours of sleeping I was not even able to re-establish the subdomain on first try.

**Comment by gaamaaresosa** [comment]
If some linux and server logic experts spend little time, one can easily make their own localtunnel server with $5/month at DO.  Also if any expert succeeded please teach me too. I am on the middle of it and keep trying...

**Comment by copleykj** [comment]
I trying to use this to while developing a Shopify app that runs on a on Meteor. This warning screen is sent every single time I refresh the embedded app as well as when the SockJS connection is established and so my web sockets never connect due to malformed JSON. I understand the reasoning behind the page and that it should only appear every 7 days, but for some reason this is not the case.

**Comment by derwaldgeist** [comment]
Hi @copleykj Good to see you here. :-) My app is actually a Meteor app as well, but I don't think this is related to Meteor in particular. This tunnel page - together with the other problem that domains cannot be re-established - renders localtunnel pretty useless for my use-case. I would really love to use it, though. So I hope there's a chance to resolve this somehow. Happy to help if I can.

**Comment by derwaldgeist** [comment]
BTW: I am also getting a 404 message or an nginx error quite often recently. The tunnel tends to break down after a while.

**Comment by copleykj** [comment]
@derwaldgeist I've only experienced the subdomain issue once and I just ended up changing the subdomain to make it work. For the most part I'm finding it more useful than ngrok which I had to pay for to get anything other than a random subdomain. Resolving the minor issues would be fantastic though.

As far as errors, I seem to be getting frequent 502 errors from nginx as well.

**Comment by derwaldgeist** [comment]
@copleykj I agree, it would be awesome if it worked reliably. Regarding the subdomain issue: I am experiencing it with all subdomains I tried.

**Comment by TheBoroer** [comment]
> BTW: I am also getting a 404 message or an nginx error quite often recently. The tunnel tends to break down after a while.

I don't know why but some websocket tunnels end up throwing piping errors, crashing the localtunnel guard which sometimes could cause other clients to disconnect...smh. I'll have to dig deeper, sorry for the inconvenience everyone! 

@derwaldgeist @copleykj 
I also use an in-memory db (I know, shame on me...but it was quick and easy at the time) for keeping track of the subdomain/ip/timestamp consent combo...so if it crashes the previous consents get wiped out. I'll switch to a persistent db so in case the services ever crash again the consent will still stay hidden for a full 7 days. my apologies


> I also noticed that the "Friendly Reminder" page does not work if you use the app inside a web view on a mobile device. If I click on "Continue", nothing happens. I have to open the same page on my desktop browser before, otherwise the app would be "broken" and has to be restarted. Tbh, I am not sure if this page is a good thing in the first place. I understand the reasoning about it, but effectively it's causing more "harm" than helping anybody.

Interesting! i will take a look at this webview issue this weekend. I'll send an update then

**Comment by derwaldgeist** [comment]
Thanks for sharing your insights, highly appreciated!

**Comment by TheBoroer** [comment]
> If some linux and server logic experts spend little time, one can easily make their own localtunnel server with $5/month at DO. Also if any expert succeeded please teach me too. I am on the middle of it and keep trying...

Try using docker and the docker instructions in these repos:
https://github.com/localtunnel/nginx
https://github.com/localtunnel/server

**Comment by derwaldgeist** [comment]
> Interesting! i will take a look at this webview issue this weekend. I'll send an update then

To be honest, for these type of scenarios, it would be better if that page was disabled in the first place. The thing is: if a web app is embedded in a native app, there's quite often some kind of glue logic that ties the two pieces together. And if the glue logic is missing (because of the info page), strange things might happen. Ok, the app should be able to deal with it, but still...

**Comment by TheBoroer** [comment]
> To be honest, for these type of scenarios, it would be better if that page was disabled in the first place. The thing is: if a web app is embedded in a native app, there's quite often some kind of glue logic that ties the two pieces together (for sending messages between native and web). And if the glue logic is missing (because of the info page), strange things might happen. Ok, the app should be able to deal with it, but still...

Is javascript blocked/limited in your webview by any chance? That would explain why the continue button won't work (it does an ajax request back to my server to save the consent before letting you continue). 

If it's your own webview app, aren't you able to set a custom user-agent or headers to tag onto all webview requests in order to  bypass the consent screen like that?

**Comment by copleykj** [comment]
My guess @derwaldgeist is that CORS is getting in the way of the XHR used to consent to the localtunnel connection.

**Comment by copleykj** [comment]
@TheBoroer 

> sorry for making everyone's lives harder, the bad guys made me do it lol

Haha, we understand that certain measures must be taken to stop potential abuse.

**Comment by derwaldgeist** [comment]
> Is javascript blocked/limited in your webview by any chance?

No, I need full JavaScript support, so it is enabled

> custom user-agent or headers to tag

Setting a custom user-agent might break certain other functionalities, like YouTube integration and such. But I could add a header, if that makes sense. Which header would I need?

**Comment by TheBoroer** [comment]
> No, I need full JavaScript support, so it is enabled
In that case, I'm not sure why the continue button wouldn't be working for you. I'll try to reproduce this issue sometime.

> Setting a custom user-agent might break certain other functionalities, like YouTube integration and such. But I could add a header, if that makes sense. Which header would I need?

I've added the header `Bypass-Tunnel-Reminder` (you can set its value to be anything, e.g. true) which should let you bypass the reminder page within your app's webview :)   lmk if that works for you!  I'll add that tip/documentation to the tunnel reminder page when I get a chance.

**Comment by derwaldgeist** [comment]
Sounds good! So I guess I'll have to add this as an HTTP header? I thought it would be in the HTML header. I'll have to figure out if Meteor allows to set the default HTTP header somehow.

**Comment by TheBoroer** [comment]
> Sounds good! So I guess I'll have to add this as an HTTP header? I thought it would be in the HTML header. I'll have to figure out if Meteor allows to set the default HTTP header somehow.

Yeah sorry I should have clarified. It has to be an HTTP header or something the client side would have to set (e.g. changing the client's user-agent works too). It would kind of defeat the purpose of the tunnel reminder page if you could bypass it by doing something server-side including adding something to the html header tag because the phishing guys would just do that to bypass and lure in their victims. 

Were you talking about webview as in a mobile app with an in-app browser that loads your tunnelled site? Do you control the app too? If yes to both of thess, I saw some things on stackoverflow that show you can change your mobile app's webview code to intercept each request (i only saw it for ios and android)

**Comment by derwaldgeist** [comment]
Ok, thanks for the clarification. Yes, we have control over the app, but it's embedded in Unity and we're using a native plugin here, so we don't have full control over the integration. In case you're curious, you can find our app at https://marblear.com (or in the app stores as "Marble Moments").

**Comment by TheBoroer** [comment]
Hey @derwaldgeist @copleykj 
I just had some free time to push an update to my localtunnel-guard service. I ditched the in-memory db and it'll now persist the 7day ip/subdomain combo. You'll only see the tunnel reminder page once per 7 days, per subdomain, per public IP. I hope that helps you guys out a bit.

By the way, cool app idea @derwaldgeist! Can you let me know what user-agent your unity native plugin sets?

**Comment by gaamaaresosa** [comment]
After several days of learning I could see the localtunnel is working on my cloud server now.
But some thing still missing.
I wanted to show some static html home page on my main Eg: domain.com
And I need the localtunnel only on my sub domain Eg:  lt.domain.com
Is it possible to do both task in one droplet with single domain ?
Can some one help me to configure /etc/nginx/nginx.conf and /etc/nginx/conf.d for this ?

Btw, I use localtunnel suggested nginx conf files.

**Comment by wesbos** [comment]
Having this issue too. I'm running Snipcart, which needs to crawl a public page to verify products/prices, but it's hitting this URL instead. Any idea how to bypass this url?

**Comment by TheBoroer** [comment]
> Snipcart

If you have control over the snipcart crawling options, just add a HTTP header `Bypass-Tunnel-Reminder` with any value (e.g. true) and you'll be good to go!

If you can't control the crawler's HTTP request header options then I'm sorry, you're out of luck here. Try the other open alternative servers listed in the issues or ngrok.

**Comment by gaamaaresosa** [comment]
@TheBoroer : Cloudflare and Firewall for security.
You advice to secure the own localtunnel server would be highly appreciated.

1) I couldn't succeed enabling ufw (Even cloud firewall).
    Since localtunnel randomly using the tcp ports for each clients, what are the ports we could block ?
    
2) Thought of using Cloudflare as a middleman, and in that case also the tunneling is not working.

**Comment by TheBoroer** [comment]
@gaamaaresosa You won't be able to use cloudflare's security or cdn or any other services (except plain dns control) with this server.

1. For security, you'll have to depend on the software and firewall installed on your linux server. I think the main port you need to worry about is the SSH port. Instead of blocking, you could install something like fail2ban and setting up 2FA logins so your server wont get brute forced. I wouldn't block any specific ports on your localtunnel installation since like you said, localtunnel uses random tcp ports for each client.

2. The reason for not being able to use cloudflare as a middleman with a localtunnel server out of the box is because localtunnel uses random tcp ports but Cloudflare only proxies through a handful of standard ports unless you're paying for their enterprise plan.

**Comment by gaamaaresosa** [comment]
> @gaamaaresosa You won't be able to use cloudflare's security or cdn or any other services (except plain dns control) with this server.
> 
> 1. For security, you'll have to depend on the software and firewall installed on your linux server. I think the main port you need to worry about is the SSH port. Instead of blocking, you could install something like fail2ban and setting up 2FA logins so your server wont get brute forced. I wouldn't block any specific ports on your localtunnel installation since like you said, localtunnel uses random tcp ports for each client.
> 2. The reason for not being able to use cloudflare as a middleman with a localtunnel server out of the box is because localtunnel uses random tcp ports but Cloudflare only proxies through a handful of standard ports unless you're paying for their enterprise plan.

Excellent thanks TheBoroer !
Since how many days I was wandering without any clue.
I will explore fail2ban to know what is that and how to handle...

**Comment by gaamaaresosa** [comment]
> 1. fail2ban

Just now

**Comment by gaamaaresosa** [comment]
>>fail2ban and setting up google 2FA logins.
These 2 steps successfully down a while ago.
Experts like you helping us a lot and teaching many new things.
Thanks again TheBoroer !

**Comment by gaamaaresosa** [comment]
@TheBoroer:
>>fail2ban and setting up google 2FA logins.
These 2 steps successfully down a while ago.
Experts like you helping us a lot and teaching many new things.
Thanks again TheBoroer !

**Comment by gaamaaresosa** [comment]
@TheBoroer : Could you please help me to make a log file on localtunnel server ?
I spend several hours and I couldn't find at which point I could write a simple log file.
I mean when a client device contacting this server with few options, like --port = 5000, --subdomain = xyz, --host = https://myhost.com 
I need to trap these information and write a log file.
Please tell be which js file and which function we could get these information ?

**Comment by ErtYwek** [comment]
_"host phishing portals_" Remind me how are used freewebhostings and CDN services like netlify. Unfortunately, everyone gets worse experience due to those people.

**Comment by fuadsayef** [comment]
If those using localtunnel to expose the api url are getting this page, it's easy to bypass it in the background.

**Comment by yashwanth2714** [comment]
@fuadsayef Can you please tell me how to do it?

**Comment by Jayanth-MKV** [comment]
https://stackoverflow.com/a/77764864

**Comment by OtmaniCodes** [comment]
Does the page still load when the service is only used for receiving webhooks and callbacks?

**Comment by TheBoroer** [comment]
> Does the page still load when the service is only used for receiving webhooks and callbacks?

If the service making the callback/webhook sends the request using a user-agent header value that looks like a legitimate web browser's user agent then yep you'll still get the reminder page. Most services that send callbacks/webhooks use a non standard user agent though so those requests should pass by fine

**Comment by wotchokoceleste-wq** [comment]
Please — I’d like to expose my Node‑RED dashboard using localtunnel and bypass the public‑IP landing page so the dashboard is shown directly. How should I proceed, please?

**Comment by gaamaaresosa** [comment]
I would suggest Cloudflare tunnel the best

⁣gaamaa

​
