### ISSUE TITLE
Access to API fails because of CORS on Tunnel-Reminder page

### ISSUE THREAD

**Issue by alvelvis** [localtunnel/localtunnel#405]
Hi everyone,
I set my API using localtunnel. It works fine and my server already allows cross domain requests, however, the TunnelReminder page does not allow cross domain requests and that makes it impossible to do any request to the server because it won't even read the "Bypass-Tunnel-Reminder" header.

I'm using this bit of JS,

```javascript
$.ajax({
    url: localtunnel_url,
    type: 'POST',
    headers: {'Bypass-Tunnel-Reminder': 'true'},
    data: form
})
```

which works fine if I execute it in a console inside my localtunnel domain, but if I'm outside it I get the `No 'Access-Control-Allow-Origin' header is present on the requested resource.`. Like I said, my server allows crossdomain requests, it's the tunnel reminder page that does not.

**Comment by mdkalish** [comment]
I ran into the same issue. I fixed it by opening the backend tunnel address on my desktop browser and accepting the tunnel warning. Then the requests from my frontend started hitting the backend server correctly. It has to be done once for every new tunnel.

**Comment by Andres6936** [comment]
Is there any way to avoid the problem without manual intervention?

**Comment by TheBoroer** [comment]
Hey all,

Unfortunately, there's no way to bypass the tunnel reminder page at this time.
You'll have to manually accept the warning once per public ip per tunnel subdomain and then all your requests should be good to go.

If that doesn't suit your use-case, some solutions:
- self-host an instance of localtunnel server using your own domain
- use another service. e.g. ngrok

Yall can thank all the bad guys / bad bots that abuse the service by flooding the public server with malware drop sites and phishing portals which causes the entire domain (and all subdomains) to be blocked by almost all major browsers for being unsafe.

@alvelvis 
I did just push a change to the tunnel reminder page though. I realized 401 errors are kind of common and might be mistaken as your own site or API unauthorized responses. It'll now return a `511` http status to be a more clear that it's a status from the proxy (localtunnel) instead of your local server. I've also opened cors up on the reminder page so that your ajax requests will at least return a 511 status code instead of cors errors. Again, this won't help you avoid the tunnel page but should help with reminding you to accept the warning first in another tab before requests work as expected (e.g. you could auto-open the tunnel url in a new tab if a 511 error is present)
