### ISSUE TITLE
x-forwarded-port header value is incorrect

### ISSUE THREAD

**Issue by JaZo** [localtunnel/localtunnel#482]
All requests have an `x-forwarded-port` header, but they have an incorrect value. A tunnel is always over HTTPS, so the port should be 443, but currently it is 80. This makes libraries like Symfony think the url is something like `https://xxx.loca.lt:80/xxx`.

**Comment by TheBoroer** [comment]
Ah good catch! I think this has something todo with the public localtunnel instance being behind a nginx reverse proxy.
I'll see if i can push a fix today!

**Comment by TheBoroer** [comment]
### Update:

So the `x-forwarded-port` shouldn't have been added at all, t'was a mistake on my end. 
Thanks for catching this. I've deployed a fix.

The only `x-forwarded-*` headers you should be seeing now is: `x-forwarded-proto` and `x-forwarded-for`

**Comment by JaZo** [comment]
Thanks for the quick reply! I really liked the `x-forwarded-*` headers as that makes libraries like Symfony use the tunnel address as host instead of localhost. I'm using localtunnel to develop a webhook and the external service requires me to verify a signature which includes the hostname. With the `x-forwarded-*` headers it works out of the box, but now I need a workaround to use the tunnel address instead of the hostname Symfony sees when verifying the signature. Is there a way to get these headers back?

**Comment by TheBoroer** [comment]
Hey @JaZo, What header do you need and what should it be set to for your setup to work?
`x-forwarded-proto` and `x-forwarded-for` are still there. x-forwarded-for should be set to the public localtunnel hostname and x-forwarded-proto should be http or https (depending on whether you accessed the link via https:// or not). 

I think the only thing that shouldn't have been set is the port header since its the same as http/https.

**Comment by Divi** [comment]
Hello @TheBoroer, I'm joining this issue because I can't find the `x-forwarded-host` header for a week~.
I wonder if you deleted it by mistake.

For the context, our app relies on multiple domains for the same codebase, and I need to detect if the forwarded domain is *.loca.lt to override the real domain. Moreover, I need to delete the usage of our local CDN in order to show the image from the localtunnel domain.

Thanks!

**Comment by JaZo** [comment]
@TheBoroer I'd like to have the `x-forwarded-host` header with the localtunnel hostname, just like @Divi mentions. `x-forwarded-for` should be used for the client IP, not the localtunnel hostname.

**Comment by TheBoroer** [comment]
Hey @JaZo and @Divi 
Sorry for the delayed reply, i totally forgot to take another look at this.

Sorry for the missing `x-forwarded-host` header. I was fixing another bug related to the forwarded proto/for headers and didnt realize x-forwarded-host was missing (i didnt think I was missing but for some reason i though the `host` header was the forwarded-host header...oops)

I think I've fixed it now :)
please let me know if I happened to mess something else up with my fat fingers lol

**Comment by Divi** [comment]
Thanks @TheBoroer, works like a charm 😁

**Comment by mubashir-kwanso** [comment]
I am using devtunnel for chargebee webhook events.

Chargebee has listed the IPs from which they send the webhook event requests.

But somehow I am getting wrong IP in `request.ip` and `request.headers["x-forwared-for"]`. None of these match the IPs listed in Chargebee docs.

If I use ngrok, I get correct IP in `request.headers["x-forwared-for"]`.

@TheBoroer
