### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by nboano** [localtunnel/localtunnel#491]
![image](https://user-images.githubusercontent.com/63854565/165556758-75d8378b-3313-4628-bb23-af26f76f4d7a.png)

**Comment by xhalo32** [comment]
I suggest making your own server, I stopped using the public localtunnel server ages ago. There's no free lunch here.

**Comment by TheBoroer** [comment]
Hey, I just checked and the server seems to be working fine.
I'd suggest checking if your firewall is blocking the connection to that port, just like the errors says.

If it's still not working, i'd suggest setting up your own server (on your own domain) and testing it out there.
I've been busy trying to fight off abusers (people hosting malware/phishing portals on this service) and the server has been going down frequently since code changes need me to restart the node services. 😞

**Comment by nboano** [comment]
Now it's working just fine. Thanks!
