### ISSUE TITLE
Localtunnel server is down.

### ISSUE THREAD

**Issue by suryarocks11** [localtunnel/localtunnel#500]
Hi,
I am not able to tunnel my local host. Seems like it's down today.

**Comment by nucleiis** [comment]
Same here!

**Comment by suryarocks11** [comment]
I guess it's up now..

**Comment by suryarocks11** [comment]
Its down again :( .

**Comment by umobiajulu** [comment]
I replicated local tunnel on https://stunel.io give it a try guys. I also added extra feature that lets you request a subdomain with a predefined password so that whenever you request the same subdomain with the same password, the system will kill the previous client and grant access to the new request. This solved the persistent problem of a subdomain running in background but your client can't connect therefore denying your access to a subdomain that is not in use.

**Comment by TheBoroer** [comment]
FYI, localtunnel should be back up and running! Thanks for your patience.
