### ISSUE TITLE
Can I use local tunnel for load testing ?

### ISSUE THREAD

**Issue by 0xvoila** [localtunnel/localtunnel#505]
I have local API (on k8s cluster minikube) and want to load test it from remote server. I am using localtunnel to expose the local API. 

Now with `artillery` load testing tool, I am going to fire hundred of thousands of requests to the exposed API. My question is would it impact or abuse any local tunnel service in between like localtunnel.me ?
Are there any limitations at all or is it like open field ?

**Comment by TheBoroer** [comment]
Hi,

The public server isn't designed for users to test load on their local setups and it's basically an open field at the moment but that might change some time in the future if there's too many people trying this out. 

Although you can give it a try, I don't think it would make sense to use localtunnel to get reliable load test results since the localtunnel vps would most likely be your bottleneck; you'd really be load testing the already busy localtunnel server which is serving  thousands of other tunnels at the moment and has limited bandwidth.

For your use case, I'd recommend you temporarily spin up a cheap VPS and setup your own instance of localtunnel server then point your `lt` client to there instead and do your testing.

**Comment by cayter** [comment]
Why would anyone do load testing on local machine? That is already a big red flag as load testing is meant to test how resilient/robust your workload is on the cloud, left alone your local machine have other processes that are computing for CPUs/RAMs which leads to inaccurate benchmarking.

**Comment by 0xvoila** [comment]
Thanks for the reply. I tried setting up my own local tunnel server , however it does not work. 

@cayter : you are right, we should not test on local. 
My only idea was to quickly check how my code is performing.
I thought of using the local only because I have big heavy machine with 32GB RAM.
