### ISSUE TITLE
[question] Is it okey to use localtunnel with long poll api?

### ISSUE THREAD

**Issue by godlikeswan** [localtunnel/localtunnel#522]
I have an app that use such a technology. After start there are sometimes 502, 504 errors and sometimes xhr gets html instead of json (looks like there is some buffer inside)

**Comment by pke** [comment]
It seems with SSE long polling it often gives 504.

**Comment by TheBoroer** [comment]
Hey! Unfortunately long polling isn't supported by the public localtunnel server at the moment due to 2 reverse proxies being between the web visitor/client and the tunnelled server. The 502 or 504 errors comes from the reverse proxies due to timeouts being set.

If you need long polling I suggest you self-host the localtunnel server on your own domain :)

**Comment by pke** [comment]
Thanks @TheBoroer for clearing that up. I guess @godlikeSwan can close this issue then ;)
Are you aware of any (commercial) solution that supports long polling?

**Comment by godlikeswan** [comment]
Yeah, thanks for the answer
