### ISSUE TITLE
Cannot Create Tunnels

### ISSUE THREAD

**Issue by biscuits4cheese** [localtunnel/localtunnel#533]
Hello,
I can no longer create new tunnels.

The 'lt' command just hangs.

Anyone else finding similar?

**Comment by DmitrySkibitsky** [comment]
Similar problem

![image](https://user-images.githubusercontent.com/20288556/197537958-95537f6c-9a2a-490a-942b-f4349a3b2d66.png)

**Comment by 107zxz** [comment]
Seems to be another certificate issue. We'll need to wait for them to be renewed

**Comment by hello96** [comment]
Same here!

**Comment by squeakycheese75** [comment]
same

**Comment by llowevad** [comment]
same here

**Comment by umer-onschedule** [comment]
Facing same issue.
A workaround is to use _-h http://localtunnel.me_ when initializing (notice http instead of https)
and open http link instead of https in browser

_Originally posted by @mybottt in https://github.com/localtunnel/localtunnel/issues/332#issuecomment-564689425_

**Comment by umer-onschedule** [comment]
> Seems to be another certificate issue. We'll need to wait for them to be renewed

use -h http://localtunnel.me when initializing (notice http instead of https)

> Worked for me

**Comment by TheBoroer** [comment]
Hey everyone!
Thanks for flagging it being an ssl issue. I have two certbots running for this project and they seem to be conflicting sometimes smh. Things should be back up and running & I'll try to tweak my certbot setup so that this doesn't happen again.

If anyone's a certbot wiz and happens to see this comment, I'd love to know if I can have 1 certbot instance do 2 types of challenges in one (i have to do http challenges for localtunnel.me since I dont control the domain name). My current setup is:

- the first certbot: runs in http challenge mode for `localtunnel.me` and `www.localtunnel.me` (using a docker container with the certbot cli running on a cron)
- the second certbot: runs in dns challenge mode for `loca.lt` and `*.loca.lt` wildcard certs (using the certbot/dns)

**Comment by biscuits4cheese** [comment]
Hi Boro,
Thanks for resolving this issue.
