### ISSUE TITLE
`localtunnel` to a dockerized `traefik` proxy

### ISSUE THREAD

**Issue by infojunkie** [localtunnel/localtunnel#577]
I have been running a dockerized application locally that uses `traefik` as a router. [Here is the relevant traefik setup](https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml#L282-L290).

Now I need to expose my local application to the Internet for some additional testing. I am trying to use `localtunnel` for that, using `lt --port 8000` but I get "404 page not found" when I hit the localtunnel URL. Same happens with ngrok (free plan).

On the other hand, if I hit a service that's not managed by `traefik`, `localtunnel` works correctly.

How can I go about debugging and fixing this issue?

**Comment by blazmrakgid** [comment]
what request do you have to make on in browser to get response from traefik? http://localhost:X (I'm guessing 80).

**Comment by infojunkie** [comment]
In my particular case, I am aliasing `localhost` to something like `myapp.docker.local` in `/etc/hosts`. So the request goes to that alias. I did test without the alias (straight to `localhost`) and got the same result.

**Comment by blazmrakgid** [comment]
change the port from 80 to something else. Try request to `localhost:8080` first, then `lt --port 8080`.

**Comment by infojunkie** [comment]
Sorry, I should have said I'm already using port 8080. Any hints for debugging / troubleshooting would be appreciated.

**Comment by blazmrakgid** [comment]
The config you linked goes to port 80, or am I misunderstanding something?

**Comment by blazmrakgid** [comment]
ok, do these in order:

1. start your app on localhost:8080, no traefik
2. make a request to your app in browser/curl/postman just to confirm that it is working
3. if that works, do `lt --port 8080` and make a request to the generated url FAST (last couple of months are rough with localtunnel, I can have the host public for a couple of minutes and then the connection drops)
4. if that doesn't work, you fucked something somewhere on your machine. I'm guessing you are on linux, if so, good luck 😄 It might be worth creating a simple hello world express app (or whatever your language of choice is) and trying to expose it at this point. If that fails, you are on your own, because it is definitely your machine.

If the above worked do the same shit, but with docker compose. You don't need to fuck with your aliasing network bullshit, that is what you have DNS/localtunnel for... Unless you know what you are doing... However, I'm just a retarded dev and networking stuff scares the shit out of me 🤣

**Comment by infojunkie** [comment]
lol thanks. I confirm that `lt` works when `traefik` is not in the picture. Unfortunately, I don't have the option of removing it, or changing the `/etc/hosts` alias (which makes no diff to the problem).

**Comment by infojunkie** [comment]
I think we can close here. I need to dig deeper into the networking layer of my OS.
