### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by Parking-Master** [localtunnel/localtunnel#595]
Seems like my website will not load, and returns a 504 timeout after a while…

**Comment by Parking-Master** [comment]
Update: It is now returning a 502 bad gateway

**Comment by TheBoroer** [comment]
Hey, can you check now? 504 probably was because your tunnel got stuck or something but i restarted the server just in case (that's why you saw the 502 for a bit).

Btw, how the heck are you noticing downtime so quick?? Wth are you using localtunnel for and are you monitoring your localtunnel site like 24/7?? 😂

**Comment by Parking-Master** [comment]
@TheBoroer lol I like to admire my projects and use them sometimes, so I check the website every few minutes 😂 also thanks it’s working again!

**Comment by ZainAli104** [comment]
@TheBoroer I want to use it just for verifying server auths but it does not work as well, so we should use its alternatives?
