### ISSUE TITLE
Tunnel Reminder

### ISSUE THREAD

**Issue by Parking-Master** [localtunnel/localtunnel#615]
So I've been thinking, why does every tunnel require a friendly reminder page? Isn't that up to the creator if they want to take the risk of abusers? An option to bypass it when starting a server would be nice.

Something like this:
```
const tunnel = await localtunnel({ subdomain: "xyz", port: 8080, bypassTunnelReminder: true });
```

I have a big project I've been planning to make that uses localtunnel but I can't ever since nobody can get on my site but me.

Thanks for the amazing repository and I hope you understand!

**Comment by TheBoroer** [comment]
Hey! 

Unfortunately for your use-case, where you want to host a big project, i'd recommend you either setup a cheap VPS and hook it up to a domain (super easy and you can get one as cheap as $2.50/mth via vultr or digitalocean i think).... or use ngrok for the time being.

I dislike the tunnel reminder / ip-password gate page as much as everyone else but the abuse is against me by causing my hosting provider's IPs to be flagged as a source of phishing/malware and also causing my loca.lt domain to be flagged by browsers as dangerous. That's why I didn't allow the tunnel creator to bypass the page. Otherwise, the bad guys would just bypass it themselves (by modifying their phishing scripts) and carry on as usual.

The current version of the tunnel reminder page (IP-password protected) is working quite well when it comes to fighting off abusers, i haven't got a single phishing/malware report since implementing it. 🔥 

That being said, it's not a permanent solution and I'm still thinking about alternative ways to fight off abuse without having to use a password protected page etc. I might force people to create an account with me in order to have custom subdomains and/or tunnels last longer than like 15min or something. That way I have more data on abusers and can automatically ban them when phishing reports come in.

**Comment by Parking-Master** [comment]
Ok, thank you very much! I used to use ngrok but the funny thing is I actually like localtunnel better. Also, the account thing you said sounds like a great idea!
