### ISSUE TITLE
Documentation on privacy and how localtunnel works

### ISSUE THREAD

**Issue by acmpo6ou** [localtunnel/localtunnel#650]
Hello! Your project looks promising, thanks for creating it. However, I'm a bit concerned about the privacy of this project. Do you collect any data? Is there a privacy policy? Basically, you can read all traffic, right? Also how much does it cost running this? Where do the money come from? It would be nice to have it in the readme, answers to all these questions. Thank you!

**Comment by TheBoroer** [comment]
Hi! Your concern is valid.

Nope, no data is collected other than the subdomain,  tunnel client IP, and visitors IPs for 7 days in order for the tunnel consent Page to work. As to how localtunnel works, feel free to browse through the localtunnel server repo to see how it all works under the hood.

Yes, I could technically am able to inspect all the traffic but don't do any snooping.

Costs are negligible/low since I run the docker containers for this public server alongside my other projects on the same dedicated server.

I can certainly add these questions to the readme. I will remind you that I run this server as a volunteer, I get nothing out of running it other than helping others like myself that need this tool. If you'd prefer a more private setup with a corporation backing it, feel free to checkout ngrok :)

Please let me know if you have any other questions

**Comment by acmpo6ou** [comment]
Thank you for your quick response and for explanation. Also, are you the only one running this? Or are there more volunteers?

**Comment by TheBoroer** [comment]
No problem! I'm the only one hosting the public server :)
