### ISSUE TITLE
Localtunnel should create server itself when no server is running on specified port.

### ISSUE THREAD

**Issue by vs4vijay** [localtunnel/localtunnel#91]
Hi,

This is just kind of enhancement to `localtunnel`. If anyone want to share his local files to internet then he first creates a dummy server (using python or node) to serve a particular directory and then creates tunnel to point that server using `localtunel`. Shouldn't be there any functionality by default in `localtunnel` to do this?

What I currently do is:

  - Create http server using `http-server /home`
  - Then point localtunnel to it using `lt --port 8080 --subdomain vs4vijay`

And I think firing `lt --port 8080 --subdomain vs4vijay` command should be enough to create server and tunnel it if no server is running on port `8080`.

**Comment by defunctzombie** [comment]
Localtunnel is about just being a proxy and not serving static files. There are plenty of tools in many languages that already do that for all sorts of flavors. No need in adding it here IMO since it would lead to more feature creep with folks wanting their specific static files served a certain way.

What you do now is simple enough :)
